version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "wednesday"
    groups:
      github-actions:
        patterns:
          - "actions/*"
      docker-actions:
        patterns:
          - "docker/*"
